"""create properties table

Revision ID: 556eb9c309ee
Revises: 8d60bbbe16b9
Create Date: 2025-06-20 17:34:20.940797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556eb9c309ee'
down_revision: Union[str, None] = '8d60bbbe16b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('suburb', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('property_type', sa.Enum('House', 'Townhouse', 'Apartment', name='propertytypeenum'), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('car_spaces', sa.Integer(), nullable=False),
    sa.Column('square_meters', sa.Integer(), nullable=False),
    sa.Column('price_min', sa.Float(), nullable=False),
    sa.Column('price_max', sa.Float(), nullable=False),
    sa.Column('annual_rent_min', sa.Float(), nullable=False),
    sa.Column('annual_rent_max', sa.Float(), nullable=False),
    sa.Column('expected_price', sa.Float(), nullable=True),
    sa.Column('expected_rental_income', sa.Float(), nullable=True),
    sa.Column('strata_fees', sa.Float(), nullable=True),
    sa.Column('council_rates', sa.Float(), nullable=True),
    sa.Column('water_rates', sa.Float(), nullable=True),
    sa.Column('home_insurance', sa.Float(), nullable=True),
    sa.Column('landlord_insurance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
